name: Deploy Healthcare App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Copy Files to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        source: "."
        target: "/var/www/myapp"
        port: 22
        debug: true

    - name: Install Backend Dependencies and Start Backend
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd /var/www/myapp/backend
          python3 -m pip install -r requirements.txt
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Install Frontend Dependencies and Start Frontend
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd /var/www/myapp/frontend
          npm install
          npm run build
          nohup npm start &

    - name: Restart NGINX
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          sudo systemctl restart nginx
